name: Main Triggers
on:
  workflow_dispatch:
    inputs:
      skip_tests:
        required: false
        type: boolean
        default: false
        description: 'Skip tests'

jobs:
  publish-package:
    name: publish main branch
    uses: ./.github/workflows/deployment.yml
    with:
      skip_tests: ${{ inputs.skip_tests }}
    secrets: inherit
