name: Main Triggers
on:
  workflow_dispatch:
    inputs:
      node_version:
        required: false
        type: boolean
        default: false
        description: 'Skip tests'

jobs:
  publish-package:
    name: publish main branch
    uses: ./.github/workflows/deployment.yml
    with:
      node_version: ${{ inputs.node_version }}
    secrets: inherit
