name: Main
on:
  workflow_dispatch:
    inputs:
      node_version:
        required: true
        type: string
        description: 'Node version'

jobs:
  publish-package:
    name: publish main branch
    uses: ./.github/workflows/deployment.yml
    with:
      node_version: ${{ inputs.node_version }}
    secrets: inherit
